### ISSUE TITLE
Desktop player goes into an infinite loop

### ISSUE THREAD

**Issue by Antiemes** [protodomemusic/mmml#3]
Desktop player does not handle when buffer1=15 and 6<=buffer2<15. Compiler generates buffer1=15, buffer2=6 for goblin-shark.mmml

**Comment by protodomemusic** [comment]
Ah ha! Thanks very much for the heads up on this. That looks like an issue with the tie command, which was implemented for another project. I didn't check the compatibility with the existing 1-bit players. If you removed all the '&' in the mmml document before compiling, it should play correctly.

I'll go through and fix every instance where this occurs this evening.

**Comment by protodomemusic** [comment]
Forgot about this - fixed (I think). Thanks again Antiemes.

**Comment by Antiemes** [comment]
Thank you very much for the fix! I will test it soon.
